config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "postings/new" => "author#create_form", as: :create_posting_form
  post "postings/create" => "author#create_posting", as: :create_posting
  get "postings/:id/update" => "author#update_form", as: :update_posting_form
  patch "postings/:id/update" => "author#update_posting", as: :update_posting
  get "postings/:id/revise" => "author#revise_posting_form", as: :revise_posting_form
  patch "postings/:id/revise" => "author#revise_posting", as: :revise_posting

  get "postings/:id/request_review" => "author#request_review", as: :request_review
  get "postings/:id/review" => "editor#review_posting", as: :review_posting
  get "postings/:id/approve" => "editor#approve_posting", as: :approve_posting
  get "postings/:id/reject" => "editor#reject_posting", as: :reject_posting
  get "postings/:id/publish" => "author#publish_posting", as: :publish_posting
  get "postings/:id/archive" => "author#archive_posting", as: :archive_posting
  get "postings/:id/delete" => "author#delete_posting", as: :delete_posting
  get "postings/:id/cancel_delete" => "author#cancel_delete_posting", as: :cancel_delete_posting
  get "postings/:id/delete_form" => "author#delete_posting_form", as: :delete_posting_form

  get "postings/:id/show" => "author#show_posting", as: :show_posting

  get "editor/dashboard" => "editor#dashboard", as: :editor_dashboard
end

app/controllers/author_controller.rb
class AuthorController < WorkflowController
  def create_form
    trigger "☝ ⏵︎Create form", endpoint: "no model" do # we don't need the Model::Find step in Protocol.
      success { |ctx, contract:, model:, **| render locals: {contract: contract, form_url: create_posting_path, verb: "Create", model: model} }
    end
  end

  def create_posting
    trigger "☝ ⏵︎Create", endpoint: "no model" do # we don't need the Model::Find step in Protocol.
      success { |ctx, model:, **| redirect_to update_posting_form_path(model.id) }
      failure { |ctx, contract:, model:, **|
        render :create_form, locals: {contract: contract, form_url: create_posting_path, verb: "Correct and create", model: model} }
    end
  end

  def update_form
    trigger "☝ ⏵︎Update form" do
      success { |ctx, contract:, model:, **| render :create_form, locals: {contract: contract, form_url: update_posting_path, verb: "Update", model: model} }
    end
  end

  def update_posting
    trigger "☝ ⏵︎Update" do
      success { |ctx, model:, contract:, **| render :create_form, locals: {contract: contract, form_url: update_posting_path, verb: "Update", model: model} }
      failure { |ctx, contract:, model:, **|
        render :create_form, locals: {contract: contract, form_url: update_posting_path, verb: "Correct and update", model: model} }
    end
  end

  def revise_posting_form
    trigger "☝ ⏵︎Revise form" do
      success { |ctx, contract:, model:, **| render :create_form, locals: {contract: contract, form_url: revise_posting_path, verb: "Revise", model: model} }
    end
  end

  def revise_posting
    trigger "☝ ⏵︎Revise" do
      success { |ctx, model:, contract:, **| render :create_form, locals: {contract: contract, form_url: revise_posting_path, verb: "Revise", model: model} }
      failure { |ctx, contract:, model:, **|
        render :create_form, locals: {contract: contract, form_url: revise_posting_path, verb: "Correct and revise", model: model} }
    end
  end

  def request_review
    trigger "☝ ⏵︎Notify approver" do
      success { |ctx, model:, **| redirect_to show_posting_path(model.id) }
    end
  end

  def publish_posting
    trigger "☝ ⏵︎Publish", controller: self do
      success { |ctx, model:, **| redirect_to show_posting_path(model.id) }
    end
  end

  def archive_posting
    trigger "☝ ⏵︎Archive" do
      success { |ctx, model:, **| redirect_to show_posting_path(model.id) }
    end
  end

  # NOTE: you can also manually trigger the "Delete" link directly. we could show how to add an additional "UI state", not on the model?
  def delete_posting_form
    trigger "☝ ⏵︎Delete? form" do
      success { |ctx, model:, **| render :delete_form, locals: {model: model} }
    end
  end

  # This is an example of how to handle such type of action - no need
  # to explicitly model a "cancel" button like this.
  def cancel_delete_posting
    trigger "☝ ⏵︎Cancel" do
      success { |ctx, model:, **| redirect_to show_posting_path(model.id) }
    end
  end

  def delete_posting
    trigger "☝ ⏵︎Delete" do
      success { |ctx, model:, **| redirect_to create_posting_form_path }
    end
  end

  def show_posting
    render :show, locals: {model: Posting.find(params[:id])} # TODO: either use OP, or endpoint or add show to <ui>?
  end
end

app/views/author/create_form.html.erb
<%= verb %> blog post

<%= simple_form_for(contract, url: form_url, as: :posting) do |f| %>
  <div><%= f.error_notification %></div>
   <%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
  <div><%= f.input :content, label: "Your text", as: :text, required: false %></div>
  <div><%= f.button :submit, value: "Submit!" %></div>
<% end %>

<ul>
    <li><%= link_to "✅ Request review", request_review_path(id: model.id || "---") %></li>
</ul>

app/views/author/delete_form.html.erb
<h1>Delete <%= model.id %>?</h1>

<ul>
  <li><%= link_to "Cancel", cancel_delete_posting_path(model.id) %></li>
  <li><%= link_to "Delete!", delete_posting_path(model.id) %></li>
</ul>

app/views/author/show.html.erb
<h1>Posting</h1>

<div class="name">
  <%= model.content %>
</div>

<div class="name">
  <%= model.state %>
</div>


<ul>
  <li>
    <%= link_to "Update", update_posting_path(model.id) %>
  </li>
  <li>
    <%= link_to "Publish", publish_posting_path(model.id) %>
  </li>
  <li>
    <%= link_to "Archive", archive_posting_path(model.id) %>
  </li>
  <li>
    <%= link_to "Delete", delete_posting_form_path(model.id) %>
  </li>
  <li>
    <%= link_to "Revise", revise_posting_form_path(model.id) %>
  </li>
  <li>
    <%= link_to "New", create_posting_form_path(model.id) %>
  </li>
  <li>
    <%= link_to "Review", review_posting_path(model.id) %>
  </li>

</ul>